config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :restaurants do
  # collection do
  #   get ''
  resources :reviews, only: [ :new, :create ]
end


# get "restaurants/:restaurant_id/reviews/new", to: "reviews#new", as: :new_restaurant_review
# post "restaurants/:restaurant_id/reviews", to: "reviews#create", as: :restaurant_reviews
# get "restaurants/new", to: "restaurants#new", as: :new_restaurant
# get "restaurants/:id", to: "restaurants#show", as: :show
# post "restaurants", to: "restaurants#create", as: :create_restaurant
# get "restaurants", to: "restaurants#index", as: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end



# VALIDATION
# a name, an address and a category.
# categroy ["chinese", "italian", "japanese", "french", "belgian"].
# review must have a parent restaurant.
#
# destroyed, all of its reviews should be destroyed as well.

# test before route rspec spec/models

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def index
    @restaurants = Restaurant.all
  end

  def edit
    @restaurant = Restaurant.find(params[:id])

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to new_restaurant_review_path(@restaurant.id)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-bar">
    </div>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name  %>
 <%= f.label :address %>
 <%= f.text_field :address  %>
 <%= f.label :phone_number %>
 <%= f.text_field :phone_number  %>
 <%= f.label :category %>
 <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"]%>
 <%= f.submit "submit", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/edit.html.erb
<p>edit</p>

<%= render 'form', restaurant: @restaurant%>

app/views/restaurants/index.html.erb
<div>
  <ul>
    <% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
  </ul>

</div>

app/views/restaurants/new.html.erb
<p>new</p>

<%= render 'form', restaurant: @restaurant%>

app/views/restaurants/show.html.erb
<div>
  <div>
  <%= @restaurant.name %>
<%= @restaurant.address %>
<%= @restaurant.category %>
<%= link_to "See details", edit_restaurant_path(@restaurant), class: "btn btn-primary"%>
<%= link_to "Create a review", new_restaurant_review_path(@restaurant) %>
</div>


</div>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>